### PR TITLE
Heatmap missing

### PR DESCRIPTION
**Pull request by sgratzl**
see #57 and https://github.com/phovea/phovea_server/issues/16

### CODE REVIEW

**Comment by sgratzl** [comment]
note: at the moment just the coloring will be done, no dashes. 
reason: all renderers are optimized to render 1px cell heatmaps that will be scaled eventually.

**Comment by mstreit** [comment]
re dashes: I think that's fine for the initial paper submission.

**Review by thinkh — APPROVED** [review]
Looks good

**Comment by thinkh** [comment]
Thanks @sgratzl

**Pull request merged**
