### PR TITLE
Merge proportional symbol vis

### PR DESCRIPTION
**Pull request by katush**
- add proportional symbol vis
https://github.com/Caleydo/mothertable/issues/66

Note: the merge with https://github.com/phovea/phovea_vis/tree/improve_list_based_vis branch is not complete, I would need to adjust scaling for the new list base visses

### CODE REVIEW

**Comment by thinkh** [comment]
@katush should I wait until you finished the scaling or just merge? will it break something?

**Comment by thinkh** [comment]
@katush ?

**Comment by katush** [comment]
@thinkh done :)

**Comment by thinkh** [comment]
Thanks 👍

**Pull request merged**
