### PR TITLE
update brush ranges

### PR DESCRIPTION
**Pull request by katush**
update to brush ranges, so not only the first & last clicked are taken as range indicators
https://github.com/Caleydo/mothertable/issues/279

### CODE REVIEW

**Comment by thinkh** [comment]
@katush This is the result of my brushing: 

grafik

In my opinion this is not correct. Either the items that aren't highlighted should not be magnified or they should be highlighted as well...

**Comment by mstreit** [comment]
@thinkh, yes this problem is known - see https://github.com/Caleydo/mothertable/issues/278.

**Comment by mstreit** [comment]
But this issue is not urgent. let's leave the brushing as it is and move to more pressing issues.

**Comment by thinkh** [comment]
Ok, then I merge it.

**Pull request merged**
